from __future__ import absolute_import, unicode_literals, division

__all__ = ('DEFAULT_DELETE_TIMEOUT_SECONDS', 'DEFAULT_EXPIRATION_SECONDS',
           'DEFAULT_PING_SECONDS', 'DEFAULT_SHARE_ADMIN_JQUERY')

DEFAULT_DELETE_TIMEOUT_SECONDS = 0
DEFAULT_EXPIRATION_SECONDS = 180
DEFAULT_PING_SECONDS = 15
DEFAULT_SHARE_ADMIN_JQUERY = True
